# Generated by Django 4.2.7 on 2024-02-03 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_id', models.CharField(max_length=25)),
                ('agency_name', models.CharField(max_length=50)),
                ('agency_url', models.CharField(max_length=255)),
                ('agency_timezone', models.CharField(max_length=50)),
                ('agency_lang', models.CharField(max_length=10)),
                ('agency_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare_id', models.CharField(max_length=25)),
                ('origin_id', models.CharField(max_length=10)),
                ('destination_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=10)),
                ('route_short_name', models.CharField(max_length=100)),
                ('route_long_name', models.CharField(max_length=100)),
                ('route_desc', models.CharField(max_length=100)),
                ('route_type', models.IntegerField()),
                ('route_color', models.CharField(max_length=10)),
                ('route_text_color', models.CharField(max_length=10)),
                ('route_url', models.CharField(max_length=100)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subway_surfer.agency')),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_id', models.IntegerField()),
                ('shape_pt_lat', models.FloatField()),
                ('shape_pt_lon', models.FloatField()),
                ('shape_pt_sequence', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.IntegerField()),
                ('stop_name', models.CharField(max_length=100)),
                ('stop_desc', models.CharField(max_length=100)),
                ('stop_lat', models.FloatField()),
                ('stop_lon', models.FloatField()),
                ('zone_id', models.CharField(max_length=10)),
                ('stop_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=25)),
                ('trip_id', models.CharField(max_length=25)),
                ('trip_headsign', models.CharField(max_length=50)),
                ('block_id', models.CharField(max_length=10)),
                ('trip_short_name', models.IntegerField()),
                ('shape_id', models.IntegerField()),
                ('direction_id', models.IntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subway_surfer.route')),
            ],
        ),
        migrations.CreateModel(
            name='Stop_Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('stop_sequence', models.IntegerField()),
                ('pickup_type', models.IntegerField()),
                ('drop_off_type', models.IntegerField()),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subway_surfer.stop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subway_surfer.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Fare_Attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('currency_type', models.CharField(max_length=10)),
                ('payment_method', models.IntegerField()),
                ('transfers', models.IntegerField()),
                ('transfer_duration', models.CharField(max_length=2)),
                ('fare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subway_surfer.fare')),
            ],
        ),
    ]
