# Generated by Django 4.2.7 on 2023-11-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=10)),
                ('route_short_name', models.CharField(max_length=100)),
                ('route_long_name', models.CharField(max_length=100)),
                ('route_desc', models.CharField(max_length=100)),
                ('agency_id', models.CharField(max_length=10)),
                ('route_type', models.IntegerField()),
                ('route_color', models.CharField(max_length=10)),
                ('route_text_color', models.CharField(max_length=10)),
                ('route_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_id', models.IntegerField()),
                ('shape_pt_lat', models.FloatField()),
                ('shape_pt_lon', models.FloatField()),
                ('shape_pt_sequence', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.IntegerField()),
                ('stop_name', models.CharField(max_length=100)),
                ('stop_desc', models.CharField(max_length=100)),
                ('stop_lat', models.FloatField()),
                ('stop_lon', models.FloatField()),
                ('zone_id', models.CharField(max_length=10)),
                ('stop_url', models.CharField(max_length=100)),
            ],
        ),
    ]
